# Generated by Django 3.1.2 on 2020-11-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('placement', models.CharField(choices=[('ad1', 'Near slider'), ('ad2', 'After 6 post'), ('ad3', 'Before top product')], max_length=10)),
                ('expiry_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
