# Generated by Django 3.1.2 on 2020-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='upload_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
