# Generated by Django 3.1.2 on 2020-11-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201102_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='upload_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
