# Generated by Django 3.1.2 on 2020-11-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201103_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
