# Generated by Django 3.1.2 on 2020-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201103_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
