# Generated by Django 3.1.2 on 2020-11-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201103_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
