# Generated by Django 3.1.2 on 2020-11-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
