# Generated by Django 3.1.2 on 2020-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201104_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
