# Generated by Django 3.1.2 on 2020-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201108_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='home_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='price_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='Kg', max_length=10),
        ),
    ]
