# Generated by Django 3.1.2 on 2020-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201119_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
