# Generated by Django 3.1.2 on 2020-11-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_item_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipping_cost',
        ),
    ]
