# Generated by Django 3.1.2 on 2020-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_item_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
