# Generated by Django 3.1.2 on 2020-11-27 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201124_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='none', upload_to=core.models.get_image_filename, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
