# Generated by Django 3.1.2 on 2020-11-27 17:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201127_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default=None, upload_to=core.models.get_image_filename, verbose_name='Image'),
        ),
    ]
