# Generated by Django 3.1.2 on 2020-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201127_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_ne',
            field=models.CharField(default='डिफल्ट', max_length=100),
            preserve_default=False,
        ),
    ]
