# Generated by Django 3.1.2 on 2020-12-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_categories_category_ne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
