# Generated by Django 3.1.2 on 2020-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201207_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=('main.UserProfile.photo', 'profiles'), verbose_name='Profile Picture'),
        ),
    ]
