# Generated by Django 3.2.14 on 2022-11-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20221031_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
