# Generated by Django 3.2.14 on 2024-01-28 06:18

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_remove_item_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoweredBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_user_photo_path, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
