# Generated by Django 3.2.14 on 2024-01-29 05:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20240128_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=core.models.get_image_path)),
                ('is_for_bottom_section', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('post_en', models.CharField(max_length=100)),
                ('post_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=core.models.get_staff_image_path)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='Content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
